apiVersion: apps/v1
kind: Deployment
metadata:
  name: sent-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sentapp
  template:
    metadata:
      labels:
        app: sentapp
    spec:
      containers:
      - name: sentainer
        image: arpitam1991/sentool:v1.0
        ports:
        - containerPort: 8050